### ISSUE TITLE
Alternate tests for all formats, independent of jtrts.dat

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/jtrTestSuite#24]
Over the last few months we've seen at least two formats that were not in TS and that could not crack their own test vectors when put in an external file and ran like IRL.

We should automate this. Just use `--list=formats` and iterate over them.

Then, for each format:
- Run `john -format=$fmt -list=format-tests | cut -f3 > tempfile`
- Run `john -format=$fmt -list=format-tests | cut -f4 > tempdict`
- Perhaps `cat pw.dic tempdict | shuf > tempdict2` or something like that
- Finally `john -format=$fmt tempfile -w:tempdict2`
- Verify results

**Comment by jfoug** [comment]
6374d49 Completed and now closing again.
