### ISSUE TITLE
Bail, or at least warn, on invalid options.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/jtrTestSuite#30]
I ran tests with -dev=cpu but it did not work, the default device was used. Took me a while to realize I forgot to say -pass=-dev=cpu... so that was a PEBCAK but TS should really not silently allow an invalid option!

**Comment by jfoug** [comment]
It sort of 'has' to.  All non-known options are treated as hash types, and hashes which do not exist in this build of JtR are simply silently ignored. 

I could do this however:

1. not silently skip unknown hashes. I could at least output that 'hash xxx was not found'  So in this case it would state:  "Hash -dev=cpu was not found"

That in itself may be enough.

2. I could abort with unknown param if the param leads with a '-' char.  That does catch some, but not all improper usage.

@magnumripper, what say you about these ideas?

**Comment by frank-dittrich** [comment]
Hash types never start with an `'-'`, so you could bail out on options starting with `'-'`

**Comment by jfoug** [comment]
$ ./jtrts.pl -dev=cpu -q
Unknown option: dev
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [cygwin 64-bit XOP-autoconf]
--------------------------------------------------------------------------------


See the 'unknown option: dev'

Not sure how much more you want???  Hmm, no PEBCAK type for jtrts, lol.

**Comment by frank-dittrich** [comment]
Hm, not every wrong option is rejected by jtrts.pl

I intended to run
```
(master)test $ ./jtrts.pl -passthru='--fork=8' -type sapg
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=SAP F/G                      guesses: 6935 -show=6794 0:00:00:00 DONE : Expected count(s) (6794)  [!!!FAILED!!!]
.pot CHK:SAP F/G                  guesses: 6794 0:00:00:00 DONE  [PASSED]

Some tests had Errors. Performed 1 tests.  1 errors
Time used was 3 seconds
```

But because I was confused I ran
```
(master)test $ ./jtrts.pl -passthru='--fork=8' --format=sapg
Unknown option: format
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=dynamic_0                    guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0                guesses: 1500 0:00:00:00 DONE  [PASSED]

form=dynamic_0-raw                guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_0-raw            guesses: 1500 0:00:00:00 DONE  [PASSED]

form=dynamic_1                    guesses: 1500 0:00:00:00 DONE  [PASSED]
^C
```

**Comment by jfoug** [comment]
Why did you reopen this Frank.

What confuses you about:   ```Unknown option: format```

**Comment by frank-dittrich** [comment]
When I ran into this for the first time I didn't notice the `Unknown option: format` output, because it scrolled off the screen. I was confusecd that jtrts did a full test suite run while I just wanted to test a single format.
I would have preferred jtrts.pl to bail out and stop.
When I re-ran the wrong command, I just interrupted jtrts and didn't read the output.

If I admit that this was a case of PEBKAC, will you change the default behaviour and stop processing despite wrong options specified?

**Comment by magnumripper** [comment]
This warning alone was a good enhancement but I too would prefer it to bail out, not just warn.

**Comment by jfoug** [comment]
The warning has been there forever I think it is std. Perl getopts behavior

**Comment by magnumripper** [comment]
LOL, you are right. I missed it just like @frank-dittrich because if just kept on running.
