### ISSUE TITLE
./jtrts.pl -internal -q fails for form=osc

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#31]
"caused" by https://github.com/magnumripper/JohnTheRipper/commit/546a203d4b673a6f15e3e25186b674e80a44fa18 which repeated the test hash in the canonical format used for john.pot.
```
(master)test $ ./jtrts.pl -internal -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
form=osc                          guesses:    1 -show=   1 0:00:00:00 DONE : Expected count(s) (2)(-show2)  [!!!FAILED!!!]
Some tests had Errors. Performed 295 tests.  1 errors00:00 DONE  [PASSED]
Time used was 75 seconds
```
I didn't revert this JtR addition:
```
+ // repeat hash in the same form that is used in john.pot
+ {"$dynamic_4$05de5c963ee6234dc7d52f7589a1922b$ ", "welcome"},
```
Because I think it is a TS problem. (`./john --test` doesn't fail)

**Comment by frank-dittrich** [comment]
BTW:
The jtrjs.pl output `.  1 errors00:00 DONE  [PASSED]` should also be adjusted. The `00:00 DONE  [PASSED]` part is from the last format that has been tested.

**Comment by frank-dittrich** [comment]
If john's stderr output is longer, it completely hides the jtrjs.pl output:
```
(master)test $ OMP_NUM_THREADS=1 ./jtrts.pl -prelims -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Warning: OpenMP is disabled; a non-OpenMP build may be faster
form=IPB2                         guesses: 1500 0:00:00:00 DONE  [PASSED]
```

**Comment by jfoug** [comment]
```
$ ../run/john -ses=./tst  -skip -pot=./tst.pot selftest.in --wordlist=selftest.dic -form=osc
Loaded 2 password hashes with 2 different salts (osc, osCommerce [md5($s.$p) (OSC) 128/128 XOP 768x4x2])
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
welcome          (?)
1g 0:00:00:00 DONE (2015-01-01 09:32) 8.403g/s 16.80p/s 33.61c/s 33.61C/s welcome..welcome
Use the "--show" option to display all of the cracked passwords reliably
Session completed
At Program Exit
MemDbg_Validate level 0 checking Passed
```
This is not a problem in the TS. It is telling you the truth.  JtR (right now), could only crack 1 hash.  Also, it said 2 salts, but there 'should' only be 1.

I am not sure of the issue here. It may be due to trailing ' ' chars being stripped off INSIDE of john core.  Yes, I know you wanted to make this the same as it is within john.pot, BUT I do not think you can.  I think you will have to use $HEX$2020 simply due to how the code within JtR loader.c works.

**Comment by jfoug** [comment]
Also note, this is (in theory) how it is store in the .pot file, BUT there are no trailing spaces:

$ cat tst.pot
$dynamic_4$05de5c963ee6234dc7d52f7589a1922b$  :welcome

It works within self test code, because that does not go through the loader.c trimming.  There simply is a rule that Solar added, that right-trims the hashes.

**Comment by frank-dittrich** [comment]
OK, so we need another osc hash which after conversion doesn't end in trailing spaces, but in other printable ascii characters...

**Comment by frank-dittrich** [comment]
In commit https://github.com/magnumripper/JohnTheRipper/commit/64d91c999343f7f395da83f5901dd49e341bbca0 I changed the offending hash.
Now ktrts.pl is happy.

**Comment by jfoug** [comment]
Good to hear.  I was pretty sure (but had not gotten debugger out to actually look deeper), that the problem was in loader.c's rtrim functionality.

That is how Solar wants it, and 99 out of 100 times, it IS correct.  It just suxs that 1 time that it is the wrong behavior.
