### ISSUE TITLE
jtrts.pl -passthru='--fork=8' appears to count dupes 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#33]
see https://github.com/magnumripper/JohnTheRipper/issues/988.

**Comment by jfoug** [comment]
I think I have a fix for you to test. I am not sure if this ever worked, OR if all the recent changes disturbed the complex if/else logic, and something got dropped.

**Comment by jfoug** [comment]
Try this one :  f8d7e65

**Comment by frank-dittrich** [comment]
You sometimes get results like this
```
form=dynamic_1003                 guesses: 1512 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_1003             guesses: 1500 0:00:00:00 DONE  [PASSED]
```
which is confusing and most likely depends on the number of forked processes.

I think the problem has been re-introduced by some recent changes. But the current logic is the same as we had after commit  fd417d8:
```
commit fd417d8b18b6a2cac40afbfb3c40133fdce24c55
Author: jfoug <jfoug@cox.net>
Date:   Tue Sep 23 13:27:26 2014 -0500

    .pot check now uses -show AND the original count. (for fork support)

```
