### ISSUE TITLE
support -random mode which changes the sequence of candidate passwords in a dictionary file.

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#35]
Since this simple shuffling
```
mkdir dic
mv *.dic dic
cd dic
for f in *.dic; do shuf < $f > ../$f; done
cd ..
```
helped to uncover bugs in certain formats:
```
Argument "eft" isn't numeric in numeric ne (!=) at ./jtrts.pl line 732.  
form=dynamic_29-utf8              guesses: 1229 -show= eft 0:00:00:00 DONE : Expected count(s) (1229)  [!!!FAILED!!!]
form=sha256crypt                  guesses:    0 -show=   0 0:00:00:02 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
.pot CHK:sha256crypt              guesses:    0 unk unk  [pass, but return code 256]
form=drupal7                      guesses:    0 -show=   0 0:00:00:08 DONE : Expected count(s) (1485)  [!!!FAILED!!!]
.pot CHK:drupal7                  guesses:    0 unk unk  [pass, but return code 256]
form=krb5-18                      guesses:    0 -show=   0 0:00:00:01 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
.pot CHK:krb5-18                  guesses:    0 unk unk  [pass, but return code 256]
Argument "ssword" isn't numeric in numeric ne (!=) at ./jtrts.pl line 732.
form=mssql-utf8                   guesses: 1229 -show=sswo 0:00:00:00 DONE : Expected count(s) (1229)  [!!!FAILED!!!]
Some tests had Errors. Performed 244 tests.  5 errors  3 runs had non-zero return code (cores?)
Time used was 640 seconds
```
I'd like to have a -random mode.
A first version could just support that random shuffling using `shuf`, and run in an endless loop unless an error occurs and `-stoponerror` has been specified.

A more sophisticated way shouldn't randomly shuffle the dictionary files.
Istead, you should be able to specify a seed, so that with the same seed the dictionary files will be shuffled in exactly the same way. This would make error reporting much easier, because you could just report the seed instead of copying the random dictionaty files.

**Comment by magnumripper** [comment]
We really should not call 'shuf' even in an experimental version, but do it in Perl. I think List::Util would be a good choice, http://perldoc.perl.org/List/Util.html
http://stackoverflow.com/questions/13416337/what-s-the-best-way-to-shuffle-an-array-in-perl

We have a random-seed feature in pass_gen.pl iirc, very trivial.

**Comment by magnumripper** [comment]
I'm working on this

**Comment by frank-dittrich** [comment]
May be there's not too much value in endlessly repeating the shuffle.
In 5 repeated runs with manually shuffling the dictionary files I only managed to trigger these few errors:

```
Argument "eft" isn't numeric in numeric ne (!=) at ./jtrts.pl line 732.  
form=dynamic_29-utf8              guesses: 1229 -show= eft 0:00:00:00 DONE : Expected count(s) (1229)  [!!!FAILED!!!]

form=dynamic_2004                 guesses: 1501 -show=1500 0:00:00:01 DONE : Expected count(s) (1500)  [!!!FAILED!!!]

form=sha256crypt                  guesses:    0 -show=   0 0:00:00:02 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
.pot CHK:sha256crypt              guesses:    0 unk unk  [pass, but return code 256]

form=sha256crypt                  guesses:  111 -show= 111 0:00:00:02 DONE : Expected count(s) (1500)  [!!!FAILED!!!]

form=drupal7                      guesses:    0 -show=   0 0:00:00:09 DONE : Expected count(s) (1485)  [!!!FAILED!!!]
.pot CHK:drupal7                  guesses:    0 unk unk  [pass, but return code 256]

form=drupal7                      guesses:  110 -show= 110 0:00:00:08 DONE : Expected count(s) (1485)  [!!!FAILED!!!]

form=krb5-18                      guesses:    0 -show=   0 0:00:00:01 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
.pot CHK:krb5-18                  guesses:    0 unk unk  [pass, but return code 256]

form=krb5-18                      guesses:  100 -show= 100 0:00:00:01 DONE : Expected count(s) (1500)  [!!!FAILED!!!]

Argument "ssword" isn't numeric in numeric ne (!=) at ./jtrts.pl line 732.
form=mssql-utf8                   guesses: 1229 -show=sswo 0:00:00:00 DONE : Expected count(s) (1229)  [!!!FAILED!!!]
```

**Comment by magnumripper** [comment]
Note that some formats use the n first lines of pw.dic. If shuffled, you'll probably end up missing the needed ones. My implementation in b5f0a95 does not have that problem.

**Comment by frank-dittrich** [comment]
The results of the shuffling seem to be random, despite specifying a particular seed, even if I don't change the type.
Infact, I want to be able to run
```
for i in `seq 1 1000`; do echo -n "$i "; ./jtrts.pl -q -type full -random -seed=$i -passthru="--fork=8"; done
```
all night, and then repeat the runs that found problems for just those formats that had errors, e.g.
```
./jtrts.pl -q -random -type dynamic_22 -seed=$i -passthru="--fork=8"
```
and still be sure that the dictionary file will be shuffled in exactly the same way.

**Comment by frank-dittrich** [comment]
In fact, even if I always use
```
./jtrts.pl -type full -q -random -seed=7 --passthru="--fork=8" 
```
I don't get repeatable results.
```
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
form=dynamic_22                   guesses: 1314 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
...
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
form=dynamic_35                   guesses: 1303 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
form=dynamic_2002                 guesses: 1305 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
...
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
form=dynamic_0-raw                guesses: 1316 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
form=dynamic_16                   guesses: 1306 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
form=dynamic_1004                 guesses: 1289 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
...
...

**Comment by frank-dittrich** [comment]
I think commit fbea5adec968c78a5c06889b913262a7d0c7c4f2 fixes the -seed problem.

**Comment by frank-dittrich** [comment]
No, still the suffling seems to be not reproducible:
```
$ for i in `seq 2015 3015`; do echo -n "$i "; ./jtrts.pl -type dynamic -q -random -seed=$i -passthru="--fork=8"; done
2015 -------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
form=dynamic_29-raw-utf8          guesses: 1350 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
Some tests had Errors. Performed 113 tests.  1 errors                    
Time used was 94 seconds
```
vs.
```
$ for i in `seq 2015 3015`; do echo -n "$i "; ./jtrts.pl -type dynamic -q -random -seed=$i -passthru="--fork=8"; done
2015 -------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------
All tests passed without error.  Performed 113 tests.  Time used was 94 seconds
```

**Comment by magnumripper** [comment]
List::Utils::shuffle may or may not use rand() or seeds it by itself... BUT --fork=8 will not give reproducible dupes anyway so that may be your whole problem.

**Comment by frank-dittrich** [comment]
> BUT --fork=8 will not give reproducible dupes anyway so that may be your whole problem.

Why not? Only if one forked process cracked all the remaining hashes while the others are still running you might have differences in the number of lines in the pot file.
(The sequence of lines can or course differ between runs.)
But --show should always give the same number of cracked hashes, and sort -u tst,.pot also should always produce the same result.
So, repeaded test runs with the same parameters and the same seed resulting in different errors definitely indicate that the shuffling is not deterministic.

**Comment by frank-dittrich** [comment]
Looks like the shuffling is indeed reproducible now, so there must be something else that made my test results differ.

**Comment by frank-dittrich** [comment]
The different test results in repeated runs were releted with jtrts.pl having trouble processing john's output when using --fork for builds with memdbg enabled.
May be I'll create a separate issue for that.

**Comment by magnumripper** [comment]
>> BUT --fork=8 will not give reproducible dupes anyway so that may be your whole problem.

> Why not? Only if one forked process cracked all the remaining hashes while the others are still running 

There will be variances in pot sync timing. Hmm or will there? We are not running with rules so I guess I was wrong.

**Comment by magnumripper** [comment]
> We are not running with rules so I guess I was wrong.

No I think I am right. Due to rounding, some nodes will use the same words.

**Comment by magnumripper** [comment]
We haven't implemented the "endless loop" thing. Reopening (but I'm not planning on implementing it right now)

**Comment by frank-dittrich** [comment]
> No I think I am right. Due to rounding, some nodes will use the same words. Heck, I'm not sure about this.

Yes, with syncing cracked hashes every few seconds, different system load, etc., the number of dupes in john.pot will change. If you have non-unique word lists or words that will be truncated, this can happen even without rules.
But a `sort -u john.pot` or a `./john --show` total number of cracked/uncracked hashes should still be the same.

**Comment by jfoug** [comment]
Can this be closed, or are you still looking at implementing some 'endless' loop mode?

**Comment by magnumripper** [comment]
Yeah I left it open since Frank mentioned that.

**Comment by frank-dittrich** [comment]
I'll not have time to implement this within the next days.
But I can live without that functionality.
I would just mimic the intended behaviour with
```
for in in `seq x y`
do
  echo -n "$i "
  ./jtrts -q -random -seed ...
  echo -n "$? "
enddo.
```
and may be add `-stoponerror` and exit if `$?` is > 0 instead of `echo -n "$? "`.

So feel free to close this issue.

**Comment by magnumripper** [comment]
There's nothing wrong with open "enhancement" issues though.
