### ISSUE TITLE
./jtrts.pl confused by memdbg output when using -passthru="--fork=16"

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#36]
When I repeatedly run
```
./jtrts.pl -q -passthru="--fork=16" -type dynamic"
```
(on my quad code system with HT) for a john build with memdbg enabled, I regularly but not always get errors like these:
```
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------
form=dynamic_80                   guesses: 1397 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
Some tests had Errors. Performed 113 tests.  1 errors                    
Time used was 200 seconds
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------
form=dynamic_23                   guesses: 1415 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
Some tests had Errors. Performed 113 tests.  1 errors                    
Time used was 203 seconds
```
So, -show has the expected number of cracked hashes, but guesses reports a number which is too small.

My guess is that jtrts.pl has trouble parsinf the memdbg output if that memdbg output of tifferent forked processes gets mixed likes this:
```
outleft__5       (u521-dynamic_70)
11 96g 0:00:00:00 DONE (2015-01-03 19:31) 3200g/s 12233p/s 12233c/s 18350KC/s ReplyNow__10..12346295
10 95g 0:00:00:00 DONE (2015-01-03 19:31) 3166g/s 12233p/s 12233c/s 18350KC/s limiey__18..B413
At Program Exit
At Program Exit
MemDbg_Validate level 0 checkingMemDbg_Validate level 0 checking Passed
 Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
1 87g 0:00:00:00 DONE (2015-01-03 19:31) 2175g/s 9175p/s 9175c/s 13762KC/s AB1168..3_�5
Waiting for 15 children to terminate
9 94g 0:00:00:00 DONE (2015-01-03 19:31) 2350g/s 9175p/s 9175c/s 13762KC/s SH�_�..P__9
At Program Exit
At Program Exit
MemDbg_Validate level 0 checking Passed
MemDbg_Validate level 0 checking Passed
At Program Exit
At Program Exit
MemDbg_Validate level 0 checking Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
At Program Exit
MemDbg_Validate level 0 checking Passed
MemDbg_Validate level 0 checking Passed
Use the "--show" option to display all of the cracked passwords reliably
Session completed
At Program Exit
MemDbg_Validate level 0 checking Passed
```

**Comment by jfoug** [comment]
I have a commented out block within current jtrts.pl that I think would handle this.  It is where count is < show. I was not sure on logic ,so I commented it out.

Now, just yesterday, I added a new block, for where count was > show, but show was right.  I may have to re-think this a bit.

I do not want to be too loose on validation, allowing something that is a problem to slip through, but in the same regard, we do not want to complain where there IS no problem.

**Comment by jfoug** [comment]
@frank-dittrich   try this one:  6fd783f

**Comment by frank-dittrich** [comment]
Trouble is the confusion about the memdbg output is hard to debug, because it depends on timing of the several forked processes...
Without a memdbg build or without --fork, the problem doesn't occur.
So I wouldn't enable the 3 lines of code currently commented out.

But I think you need to change the `>` into `>=`, just in case the expected number of guesses is caused by some missed passwords and some other passwords cracked by different forked processes.

**Comment by jfoug** [comment]
Have you tested out the commit 6fd783f yet ?  That did not comment out the 3 lines, it simply uses value of the show command, which is not going to get 'lost' based upon -fork or -memdbg, since all output is on a single line.

**Comment by frank-dittrich** [comment]
> Have you tested out the commit 6fd783f yet ? 

Yes, meanwhile I tested that commit.
These errors disappeared (as expected).

> That did not comment out the 3 lines, it simply uses value of the show command, which is not going to get 'lost' based upon -fork or -memdbg, since all output is on a single line.

I started writing that comment before you mentioned your commit 6fd783f.
