### ISSUE TITLE
descrypt ascii vs. non-ascii characters

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#43]
Since descrypt accepts 8bit characters, but ignores the highest bit, TS has to treat several possible password candidates as valid, as long as they match after stripping the highest bit.

```
form=descrypt                     guesses: 1500 0:00:00:00 DONE  [PASSED]
FAILED line = P�II             (PIII)
FAILED line = hello__1         (hello__�)
FAILED line = �23�5�_2         (12345__2)
FAILED line = 1__3             (1�_3)
FAILED line = P�II             (PIII)
FAILED line = 1__3             (1�_3)
FAILED line = BBSPw__5         (B�S�w_�5)
FAILED line = �23�5�_2         (12345__2)
FAILED line = 1__�             (1__1)
FAILED line = ad�in__1         (admin__1)
FAILED line = hello__1         (hello__�)
FAILED line = qerwt__2         (qe�wt_߲)
FAILED line = BBSPw__1         (B�SP�__�)
FAILED line = qerwt__2         (qe�wt_߲)
FAILED line = qerwt__5         (q�rwt_ߵ)
FAILED line = letM�in          (letMein)
FAILED line = qe��t__�         (qerwt__3)
FAILED line = admin__5         (�d�in__5)
FAILED line = ad�in__1         (admin__1)
FAILED line = test__�          (test__5)
FAILED line = 1234�__�         (12345__4)
FAILED line = test             (��st)
FAILED line = test__�          (test__5)
FAILED line = BBSPw__1         (B�SP�__�)
FAILED line = test             (��st)
FAILED line = admin__5         (�d�in__5)
FAILED line = qe��t__�         (qerwt__3)
FAILED line = BBSPw__5         (B�S�w_�5)
FAILED line = qerwt__5         (q�rwt_ߵ)
FAILED line = 1__�             (1__1)
FAILED line = letM�in          (letMein)
FAILED line = 1234�__�         (12345__4)
.pot CHK:descrypt                 guesses: 1532 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1500 val-pwd)
Exiting on error. The .pot file ./tst.pot contains the found data
The command used to run this test was:

../run/john -ses=./tst  --fork=3 -pot=./tst.pot DES_tst.in --wordlist=pw.dic
```
In the `FAILED` lines above, the test suite either expects ascii-only passwords where john found non-ascii passwords, or it expects non-ascii paswords where john found ascii passwords.

**Comment by frank-dittrich** [comment]
For some reasons, I only see these descrypt problems with `-passthru="--fork=n"`, e.g.
```
./jtrts.pl -stoponerror -v -type descrypt -passthru="--fork=2"
```
```
./jtrts.pl -stoponerror -v -type descrypt -passthru="--fork=3"
```
Without --fork, the error disappears.

**Comment by magnumripper** [comment]
I see this problem too. Totally understandable and a purely test-technical issue. Either change the dict to ensure we don't get 8-bit "alternate" candidates when using fork, or change the .pot check to strip 8th bit for the plains. I vote for the latter. We could do so for any format the doesn't have FMT_8_BIT. The first we should do is write a function in TS that can test a flag for a particular format, eg. `if (fmtflag($format, FMT_8_BIT)) { strip8(file); }`

**Comment by frank-dittrich** [comment]
With sapB we can have a similar issue.
Any 8bit character can be replaced with `'^'`, and the resulting word will still crack the hash.

Not sure whether it can be triggered with the current test data.

I wouldn't want descrypt and sapb to convert the password stored in the pot file into ascii.
So, I agree with magnum: handle the FMT_8_BIT case in the TS.

**Comment by jfoug** [comment]
I will add code to 'fix' this known issue in the TS.  But I ask , 'WHY', does this only impact -fork=n code??  @magnumripper you say this is for technical reasons. Well so be it, but why only forked code?

**Comment by jfoug** [comment]
I believe it is fixed in 670dc1c

**Comment by magnumripper** [comment]
> But I ask , 'WHY', does this only impact -fork=n code?

I did not verify this, but I assume it's because when not running fork, the "expected" plaintexts come earlier in the dictionary. When running forked, some unexpected ones beat the expected ones to it.

**Comment by frank-dittrich** [comment]
I assum that's right. So, instead of `-passthru="--fork=2"`, `-random` might have worked as well to see this.
