### ISSUE TITLE
Use of uninitialized value in split at ./jtrts.pl line 691.

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/jtrTestSuite#57]
When testing opencl, I get
```
Use of uninitialized value in split at ./jtrts.pl line 691.
Use of uninitialized value $details[4] in hex at ./jtrts.pl line 692.
```
for several formats.

I am testing opencl for Haswell with beignet.
I guess the driver debug output corrupts what ./jtrts.pl expects as --list=format-details output.

```
$ ../run/john --list=format-details --format=pwsafe-opencl
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
pwsafe-opencl	87	1	1	00000003	5	SHA256 OpenCL	Password Safe		-1	0	72	iteration count	0	$pwsafe$*3*fefc1172093344c9d5577b25f5b4b6e5d2942c94f9fc24c21733e28ae6527521*2048*88cbaf7d8668c1a98263f5dce7cb39c3304c49a3e0d76a7ea475dc02ab2f97a7
```

Would it be possible to just ignore lines which don't have enough tabs?
Or lines which don't have the format label as the first field (may be ignoring case here)?

**Comment by magnumripper** [comment]
Much of the output parsing in TS has similar problems, it should be overhauled. So much to do, so little time...

**Comment by jfoug** [comment]
@frank,

Please see if this has been fixed, if so, close this bug.
