### ISSUE TITLE
TS is too slow

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/jtrTestSuite#58]
We need to find out why it takes hours to run now, it used to take ten minutes or perhaps twenty. One problem is a few OpenCL formats that compile kernel and auto-tune as soon as you use --list options, but I think few formats still do that.

It's now so very slow it's not very appealing to use it and that's a bad thing.

**Comment by jfoug** [comment]
Is this on startup or during run.  Startup is due to this:

../run/john -list=format-details

I think that is only needed for 8-bit.  If so, then we should add another field to the jtrts.dat file, so that we can place the proper information into static data, and not have to take so long to run that command OR fix that command.

**Comment by magnumripper** [comment]
Maybe, but eventually we should really ensure any --list query is as quick as possible. First of all, `init()` should not do unnecessary things like compiling a kernel.

**Comment by jfoug** [comment]
the -list-format-details is used for:

8bit
split-case
is-salted

Can we detect which fields of the -list=format-details require init() to be called.  Possibly we could make that call work without the init() call.  I know a few things that needed it were some late created things, like the dynamic, and possibly crypt.  Why are the opencl needing init() code ?

**Comment by magnumripper** [comment]
Some time ago, all OpenCL formats built their kernels and did an auto-tune when their `init()` was called. Now nearly all of them are doing it in `reset()` instead. The ones that still doesn't are @Sayantan2048's (should be fixed) and @claudioandre's (already fixed but not yet merged iirc).

**Comment by magnumripper** [comment]
I merged Claudios stuff now.

**Comment by magnumripper** [comment]
--list=format-details took 12 seconds before that, 4 seconds after.

**Comment by magnumripper** [comment]
Now descrypt-opencl, bcrypt-opencl and mscash2-opencl are the slow ones.

**Comment by magnumripper** [comment]
> the -list-format-details is used for:

>8bit
split-case
is-salted

Is it run once for all formats, and results cached? Or is it run for each format? One 12 second delay wouldn't hurt much (and we're down to 4 seconds now). Maybe this is called many times?

**Comment by magnumripper** [comment]
Looks like it's just run once. There must be other things making TS so slow.

**Comment by magnumripper** [comment]
BTW did we not have `./jtrts.pl cpu` working? Doesn't work now.

**Comment by Sayantan2048** [comment]
Strike mscash2-opencl off the list.

**Comment by magnumripper** [comment]
I tried an internal run
```
$ OMP_NUM_THREADS=1 ./jtrts.pl -internal cpu -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-625-g2dd512c OMP [darwin14.4.0 64-bit AVX-ac]
--------------------------------------------------------------------------------
form=bcrypt                       guesses:   13 -show=  13 0:00:00:00 DONE : Expected count(s) (14)(-show14)  [!!!FAILED1!!!]
.pot CHK:bcrypt                   guesses:   12 -show=  13 0:00:00:00 DONE : Expected count(s) (14)  [!!!FAILED4!!!]  (12 val-pwd  0 inval-pwd)
form=crc32                        guesses:    4 -show=   4 0:00:00:00 DONE : Expected count(s) (8)(-show8)  [!!!FAILED1!!!]
.pot CHK:netntlm-naive            guesses:    6 -show=  11 0:00:00:00 DONE : Expected count(s) (13)  [!!!FAILED4!!!]  (6 val-pwd  0 inval-pwd)
form=oracle12c                    guesses:    0 -show=   0 0:00:00:00 DONE : Expected count(s) (1)(-show1)  [!!!FAILED1!!!]
.pot CHK:oracle12c                guesses:    0 -show=   0 unk unk : Expected count(s) (1)  [!!!FAILED4!!!]  (0 val-pwd  1 inval-pwd)
form=pbkdf2-hmac-md4              guesses:    3 -show=   2 0:00:00:00 DONE : Expected count(s) (3)(-show3)  [!!!FAILED3!!!]
.pot CHK:pbkdf2-hmac-md4          guesses:    2 -show=   2 0:00:00:00 DONE : Expected count(s) (3)  [!!!FAILED4!!!]  (2 val-pwd  0 inval-pwd)
form=pbkdf2-hmac-md5              guesses:    3 -show=   2 0:00:00:00 DONE : Expected count(s) (3)(-show3)  [!!!FAILED3!!!]
.pot CHK:pbkdf2-hmac-md5          guesses:    2 -show=   2 0:00:00:00 DONE : Expected count(s) (3)  [!!!FAILED4!!!]  (2 val-pwd  0 inval-pwd)
form=scrypt                       guesses:   10 -show=   9 0:00:00:01 DONE : Expected count(s) (10)(-show10)  [!!!FAILED3!!!]
.pot CHK:scrypt                   guesses:    9 -show=   9 0:00:00:00 DONE : Expected count(s) (10)  [!!!FAILED4!!!]  (9 val-pwd  0 inval-pwd)
Some tests had Errors. Performed 332 tests.  6 errors  6 errors reprocessing the .POT files
Time used was 327 seconds
```
Some of these might be new issues for JtR. But on topic for this issue, it's 332 formats tested in roughly 1 second each (no opencl formats, but an OpenCL build). So this speed is just fine.

**Comment by jfoug** [comment]
Is this issue handle now?

**Comment by magnumripper** [comment]
No, I think there's some other problem with more impact than the one we fixed.

**Comment by jfoug** [comment]
Can you specify exactly where 'slow' behavior is?  Is it before the tool starts? is it between tests?

For me, it is running fine.

**Comment by magnumripper** [comment]
> For me, it is running fine.

No it's not. You quoted a run recently that took over an hour. It didn't use to be anywhere near that slow

**Comment by magnumripper** [comment]
I'm not sure what part is slow, will look into it later.

**Comment by jfoug** [comment]
That was a full run (IIRC) on cygwin.  Cygwin is really damn slow for things like this (or running configure, etc).  I think it is in spawning things which both configure and the TS do a lot of.  Spawning under cygwin is about 100x slower than on a decent linux install on the same PC (but in a VM).  It may have also been a TS run on my sparc box, which is like running on a beefy pentium1 (a pentium1 with 32 cores however, lol).

**Comment by jfoug** [comment]
If you are complaining about 'full' tests, then blame net-ntlm and other crap like that (the 'non-naive' ones). Those are F'n super slow to start, and since they are also encoded, the TS runs them many times.

**Comment by magnumripper** [comment]
So maybe it's not that bad now. I usually do them including OpenCL formats, and they are terrificly slow no matter how we do it, due to kernel compiles. Not much we can do about that. I'll do a normal -q run with CPU only tomorrow, let's see.

**Comment by magnumripper** [comment]
Part of the "problem" is we have a shitload of formats. I believe the number of OpenCL formats alone now exceeds the total number of formats (including dynamic) we had prior to GPU support.

**Comment by jfoug** [comment]
Possibly we need finer granularity than 'normal' or 'full'

**Comment by magnumripper** [comment]
I think I tried "cpu" yesterday and it didn't work (it does work with -internal since it's a Jumbo "format class"). That would be a good addition.

**Comment by magnumripper** [comment]
Note that we don't need to change jtrts.dat to get a "cpu" class. We could infer it from every line that does not have "opencl" or "cuda"

**Comment by magnumripper** [comment]
I should hang up now, or telco will celebrate for months.

**Comment by jfoug** [comment]
-nontype=opencl 'should' get you similar to cpu, but I think you are right, cpu would be nice.

We have a cpu format 'class' in john, just not in the TS.

**Comment by jfoug** [comment]
have fun having fun.

**Comment by jfoug** [comment]
Is this STILL an issue?  I think things have been greatly improved, speed wise.

**Comment by magnumripper** [comment]
Yeah I think so too but haven't run a full test in a very long time. Let's close it, if we see something later we can open a new specific issue.
