### ISSUE TITLE
State / resume

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/jtrTestSuite#59]
How about resume functionality for --stoponerror? Say I run TS, it tests 114 formats then stops with an error. I fix the error and re-run (using some new --resume option). TS will start with the format that previously failed/crashed, and continue from there.

**Comment by jfoug** [comment]
What happens if the 'fix' is to disable the format?

**Comment by frank-dittrich** [comment]
I'd say just continue with the next test that isn't for a disabled format.

**Comment by jfoug** [comment]
This whole thing may need to thinking through. I am not sure that the TS has any idea what 'line number' it is on. If I can add that logic, it will not be too hard to resume. If not, then I was going to base logic on skipping work until I hit a test case that matched what was 'saved' in the restore file.  But if the format is disabled, then the filtering logic will have removed that format totally from the input data.

Let me first see if I can 'know' what line I am at, AND if they are all used in order.

**Comment by jfoug** [comment]
Part of the problem, is that the TS dynamically 'build' the data to work on (sort of like rules), BUT if john gets changed, then this rebuild of input work will not be the same as the prior run.  Hence the catch-22

**Comment by frank-dittrich** [comment]
I would just set a __JTRTS_TEST_NUMBER environment variable, and if that doesn't exist, because the user closed the old session, then start from the first test, or stop with an error message...

**Comment by frank-dittrich** [comment]
You might to store the complete __JTRTS_COMMAND_LINE as well, to resume whatever specific sub-test a user started...

**Comment by jfoug** [comment]
I did this by converting the options to a hash.  I then simply add the line number to the hash.  If resuming, I simply skip that many lines and start.  This should get us to where I 'think' we wanted to go.  Yes, you CAN fuk with it, by running a different build of john, such as with disabled formats.  But this is a helper TOOL, it is not supposed to be 100%.  The -resume as it stands will help a great deal, when a format fails, you exit (or -stop-on-error) and fix things then want to re-run.  That format will be the first thing to start out.

The file is stored in JSON.  JSON::XS is needed, along with File::Slurp   Pretty simple requirements, and saves a ton of lot of code, having me 'try' to code the file save/restore stuff.  Using this method it is a 2 line write and a 2 line read, and that is marshaling ALL of the data into and out of my options hash.

**Comment by magnumripper** [comment]
Somehow this broke `-passthru`:
```
$ ./jtrts.pl rar-opencl -pass=-dev=2
Can't use string ("-dev=2") as an ARRAY ref while "strict refs" in use at ./jtrts.pl line 150.
```

**Comment by magnumripper** [comment]
4f13c67 introduced new problems
```
$ ./jtrts.pl raw-sha1-linkedin
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1150-gbd06438+ OMP [linux-gnu 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

NO tests were performed.  Time used was 3 seconds
```
```
$ ./jtrts.pl raw-sha1-linkedin -internal
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1150-gbd06438+ OMP [linux-gnu 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
Running JTRTS in -internal mode
sh: 1: Syntax error: "(" unexpected
NO tests were performed.  Time used was 3 seconds
```

**Comment by magnumripper** [comment]
I can't use current version at all because of the bugs so I created an alternate branch 'noresume' with all that resume stuff reverted.

**Comment by jfoug** [comment]
What bugs?  Or is it because of JSON::XS ?

**Comment by magnumripper** [comment]
No, the https://github.com/magnumripper/jtrTestSuite/issues/59#issuecomment-142103760 (one page up here :arrow_up: ). It's probably trivial but I had my hands full with Unicode issues.

**Comment by jfoug** [comment]
```
$ ./jtrts.pl raw-sha1-linkedin
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1150-gbd06438+ OMP [linux-gnu 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

NO tests were performed.  Time used was 3 seconds
$ ./jtrts.pl raw-sha1-linkedin -internal
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1150-gbd06438+ OMP [linux-gnu 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
Running JTRTS in -internal mode
sh: 1: Syntax error: "(" unexpected
NO tests were performed.  Time used was 3 seconds
```

This works.  Not sure why the other is failing.  Did it work before?  Usually that is the way I use the tool, so I am not sure why it's failing now.

```
$ ./jtrts.pl -type raw-sha1-linkedin
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1213-g9cecf81+ [cygwin 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=raw-sha1-linkedin            guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:raw-sha1-linkedin        guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

All tests passed without error.  Performed 1 tests.  Time used was 1 seconds
```

**Comment by magnumripper** [comment]
I haven't ever used the -type option, but that's a workaround for now. I really need the -internal tests too, they are excellent.

**Comment by magnumripper** [comment]
It worked fine without -type prior to 4f13c67 (and it works fine in my alternate branch)

**Comment by jfoug** [comment]
I think I see what is wrong, now just have to figure it out.

```
John Jumbo build detected.
Running JTRTS in -internal mode
type=array(0x600070710)
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `../run/john -list=formats -format=array(0x600070710)  2>/dev/null'
NO tests were performed.  Time used was 1 seconds
```

This came from this change in the doInternalMode function

```
		foreach my $type (@types) {
+			print "type=$type\n";
+			ScreenOutVV("Looking for $type\n");
```

So the @types array now contains arrays, so I simply have to adjust for this (or remove the array in the start.  I am using arrays so that things are setup for ease within the JSON code (so it is a 1 liner).  I simply have to make sure that array is simply an array of flat strings.

**Comment by jfoug** [comment]
Ok, I think this is where the problem 'starts'    

my $err = GetOptions(\%opts,

When I changed to that the resultant  @ARGV gets screwed up.  It 'used' to contain values not slurped up in the call.  Now I get this ARRAY(0x.....) string (it is NOT an array, it is that actual string).

So this looks like a bug in GetOptions  (gotta love perl, lol).

**Comment by jfoug** [comment]
Found the problem, but now I need to make sure resume is working:


if (defined $opts{argv})        {@ARGV              = @{$opts{argv}}; }

I had changed that to 

if (defined $opts{argv})        {@ARGV              = split /\s+/, $opts{type}; }

and that was wrong.

**Comment by jfoug** [comment]
Try now.  I think it is working fine.  NOTE, I 'thought' that might be a problem, but was not sure how to test.  Well, looks like test was super trivial.

4400ee0

**Comment by magnumripper** [comment]
Awesome
```
$ ./jtrts.pl nt-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1239-gabd6f00 OMP [darwin14.5.0 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=nt-opencl                    guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:nt-opencl                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

form=NT-opencl-utf8               guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:NT-opencl-utf8           guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

form=NT-opencl-cp850              guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:NT-opencl-cp850          guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)

All tests passed without error.  Performed 3 tests.  Time used was 10 seconds
magnum:test [master]$ ./jtrts.pl nt-opencl -internal
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper 1.8.0.6-jumbo-1-1239-gabd6f00 OMP [darwin14.5.0 64-bit AVX2-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.
Running JTRTS in -internal mode

form=nt-opencl                    guesses:   44 0:00:00:00 DONE  [PASSED]
.pot CHK:nt-opencl                guesses:   43 0:00:00:00 DONE  [PASSED] (43 val-pwd)
All tests passed without error.  Performed 1 tests.  Time used was 2 seconds
```

I'll delete that temporary branch.

**Comment by magnumripper** [comment]
Oh, and --passthru works fine too :+1:
