### ISSUE TITLE
bcrypt-opencl fails on TS

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/jtrTestSuite#80]
http://www.openwall.com/lists/john-dev/2017/02/24/1

The Problem (1500 is expected)
```
Execute john: ../run/john -ses=tst-  -dev=7 -pot=tst-.pot BF_tst.in --wordlist=tst-pw-40.dic -form=bcrypt-opencl 2>&1 >/dev/null

Cmd_data = 
Device 7: GeForce GTX TITAN
Press 'q' or Ctrl-C to abort, almost any other key for status
300g 0:00:00:04 DONE (2017-03-01 00:24) 63.55g/s 6.567p/s 65.67c/s 9851C/s GPU:48C Skippin� an�*..12qw34er
```

To confirm the problem goes away when I change the wordlist, run:
```
../run/john -ses=tst-  -dev=7 -pot=tst-.pot BF_tst.in --wordlist=pw.dic -form=bcrypt-opencl
```

So, a fix is needed on TS. Something like this does the trick:
```
sed -i -e 's/40,Bcrypt/1000,Bcrypt/g' /jtrts.dat
```

**Comment by magnumripper** [comment]
But this worked before, didn't it? I wonder what caused this.

**Comment by claudioandre** [comment]
Since I put TS on CI recently, I'm can't say too much about bcrypt.
* I tried to test previous commits, but I only succeed confusing myself. 
* I mean, the workaround seen above is clearer than what I was able to find.

And note I'm running TS for OpenCL. In fact, I suppose I never did this before.

**Comment by magnumripper** [comment]
OK `sed -i -e 's/40,Bcrypt/200,Bcrypt/g' jtrts.dat` is enough. I will commit that.

**Comment by magnumripper** [comment]
I see now 200 is the number used for CPU format also.
